--DATA PROCESSING 
--CHECK FOR DUPLICATES B
--Are there duplicate ID numbers?

SELECT ORDER_ID, COUNT(*) AS All_data
FROM ORDERS
GROUP BY ORDER_ID
HAVING COUNT (*) > 1;
--Are there duplicate product IDs?
SELECT 
	PRODUCT_ID, 
	ORDER_ID, 
	COUNT(*) AS data_count
FROM ORDER_ITEMS
GROUP BY
	PRODUCT_ID,
	ORDER_ID
HAVING COUNT(*)> 1;

--CHECKING FOR NULLS 
--Are there missing product ids? 
SELECT * FROM ORDER_ITEMS
WHERE PRODUCT_ID IS NULL;

--MIssing quantity or price
SELECT * FROM ORDER_ITEMS
WHERE PRICE IS NULL
OR QUANTITY IS NULL;


--ORDER DATE

SELECT * 
FROM ORDERS
WHERE ORDER_DATE IS NULL;

--INVALID VALUES 
--ZERO /NEGATIVE QUANTITY
SELECT * FROM ORDER_ITEMS
WHERE QUANTITY<= 0;

--ZERO /NEGATIVE PRICE

SELECT * FROM ORDER_ITEMS
WHERE PRICE <=0;

--DATE RANGE VALIDATION

SELECT 
	MIN(ORDER_DATE) AS earliest,
	MAX(ORDER_DATE) AS latest
FROM ORDERS


--JOINS RELATIONSHIP
SELECT oi.*
FROM Order_Items oi
LEFT JOIN Product p
    ON oi.Product_ID = p.Product_ID
WHERE p.Product_ID IS NULL;

--PRODUCT WITH NO CATEGORY

SELECT *
FROM Product
WHERE Category IS NULL;
--CANCELLED ORDERS

SELECT ORDER_STATUS, COUNT(*)
FROM Orders
GROUP BY ORDER_STATUS;
